#!/usr/bin/env bash
# Complete Integration Startup Guide
# Starts backend + frontend with all AGENTS.md features

set -e

PROJECT_ROOT="/home/taylor/CUGAr-SALES"
BACKEND_PORT=8000
FRONTEND_PORT=5173

echo "=========================================="
echo "CUGAr Sales Assistant - Startup Guide"
echo "=========================================="
echo ""

# Check Python
echo "✓ Checking Python..."
python3 --version || { echo "❌ Python 3.12+ required"; exit 1; }

# Check Node
echo "✓ Checking Node.js..."
node --version || { echo "❌ Node.js required for frontend"; exit 1; }

echo ""
echo "=========================================="
echo "BACKEND STARTUP"
echo "=========================================="
echo ""
echo "Starting FastAPI backend on port $BACKEND_PORT..."
echo ""
echo "Features enabled:"
echo "  ✅ AGENTS.md Coordinator (5 REST endpoints)"
echo "  ✅ WebSocket Trace Streaming"
echo "  ✅ Profile-driven budgets (enterprise/smb/technical)"
echo "  ✅ Approval gates (human authority)"
echo "  ✅ Real-time trace events"
echo ""
echo "Run in Terminal 1:"
echo "─────────────────────────────────────────"
echo "cd $PROJECT_ROOT"
echo "PYTHONPATH=src uvicorn src.cuga.backend.server.main:app \\"
echo "  --host 0.0.0.0 --port $BACKEND_PORT --reload"
echo "─────────────────────────────────────────"
echo ""
echo "Expected output:"
echo '  INFO: Uvicorn running on http://0.0.0.0:8000'
echo '  ✅ AGENTS.md coordinator endpoints registered at /api/agents/'
echo '  ✅ WebSocket trace streaming registered at /ws/traces/{trace_id}'
echo ""

echo "=========================================="
echo "FRONTEND STARTUP"
echo "=========================================="
echo ""
echo "Starting React frontend on port $FRONTEND_PORT..."
echo ""
echo "Components available:"
echo "  ✅ ProfileSelector (profile switching)"
echo "  ✅ BudgetIndicator (real-time budget)"
echo "  ✅ ApprovalDialog (human authority)"
echo "  ✅ TraceViewer (canonical events)"
echo ""
echo "Hooks available:"
echo "  ✅ useAGENTSCoordinator (REST API)"
echo "  ✅ useTraceStream (WebSocket)"
echo ""
echo "Run in Terminal 2:"
echo "─────────────────────────────────────────"
echo "cd $PROJECT_ROOT/src/frontend_workspaces/agentic_chat"
echo "npm run dev"
echo "─────────────────────────────────────────"
echo ""
echo "Expected output:"
echo '  VITE v5.x ready in X ms'
echo "  ➜  Local:   http://localhost:$FRONTEND_PORT/"
echo ""

echo "=========================================="
echo "TESTING"
echo "=========================================="
echo ""
echo "Once both servers are running, test with:"
echo ""
echo "1. Health Check:"
echo "   curl http://localhost:$BACKEND_PORT/api/agents/health"
echo ""
echo "2. Budget Info:"
echo "   curl http://localhost:$BACKEND_PORT/api/agents/budget/enterprise"
echo ""
echo "3. WebSocket (requires wscat: npm install -g wscat):"
echo "   wscat -c ws://localhost:$BACKEND_PORT/ws/traces/test-001"
echo ""
echo "4. API Documentation:"
echo "   open http://localhost:$BACKEND_PORT/docs"
echo ""
echo "5. Frontend UI:"
echo "   open http://localhost:$FRONTEND_PORT"
echo ""

echo "=========================================="
echo "E2E TEST FLOW"
echo "=========================================="
echo ""
echo "Test the complete integration:"
echo ""
echo "1. Open browser to http://localhost:$FRONTEND_PORT"
echo "2. Switch profile (enterprise → smb → technical)"
echo "3. Verify budget indicator updates"
echo "4. Trigger an execute action"
echo "5. Verify approval dialog appears"
echo "6. Open trace viewer (Ctrl/Cmd+T)"
echo "7. Verify canonical events display"
echo "8. Check WebSocket connection status (🟢 Live)"
echo ""

echo "=========================================="
echo "TROUBLESHOOTING"
echo "=========================================="
echo ""
echo "Backend not starting:"
echo "  • Check: PYTHONPATH=src python3 -c 'from cuga.orchestrator import AGENTSCoordinator; print(\"OK\")'"
echo "  • Check: lsof -i :$BACKEND_PORT (port available?)"
echo ""
echo "Frontend not connecting:"
echo "  • Check: curl http://localhost:$BACKEND_PORT/api/agents/health"
echo "  • Check browser console for CORS errors"
echo ""
echo "WebSocket not working:"
echo "  • Check: wscat -c ws://localhost:$BACKEND_PORT/ws/traces/test"
echo "  • Check browser WebSocket inspector"
echo ""

echo "=========================================="
echo "QUICK START COMMANDS"
echo "=========================================="
echo ""
echo "# Terminal 1 - Backend"
echo "cd $PROJECT_ROOT && PYTHONPATH=src uvicorn src.cuga.backend.server.main:app --reload"
echo ""
echo "# Terminal 2 - Frontend"
echo "cd $PROJECT_ROOT/src/frontend_workspaces/agentic_chat && npm run dev"
echo ""
echo "# Terminal 3 - Tests"
echo "cd $PROJECT_ROOT && pytest tests/integration/test_agents_compliance.py -v"
echo ""

echo "=========================================="
echo "Ready to start! 🚀"
echo "=========================================="
echo ""
